### PR TITLE
fix: Shiki twoslash error displays are visually offset slightly

### LINKED ISSUE #117: 🐛 Bug: Shiki twoslash error displays are visually offset slightly
### Bug Report Checklist

- [X] I have [searched for related issues](https://github.com/LearningTypeScript/site/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

Don't have visual bugs 😄? There should be no text overflow around code snippets or shiki error annotations.

### Actual

https://github.com/LearningTypeScript/site/pull/116

Screenshot of a codeblock with a shiki twoslash error annotation. The code in the annotation has overflowed past its allowed area.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by StyleShit**
As promised... 😄 

Closes #117

Before:
image

After:
image

### CODE REVIEW

File: src/theme/CodeBlock/index.tsx [hunk 1]
```diff
@@ -17,9 +17,7 @@ export default function CodeBlockWrapper({
         className={clsx("shiki hihi", styles.codeBlock, className)}
         {...props}
       >
-        <div className="code-container line">
-          <code>{children}</code>
-        </div>
```
Comment (StyleShit) [inline src/theme/CodeBlock/index.tsx:22]: There was a duplication of `.code-container`, and `code`:

image

File: src/css/custom.css [hunk 2]
```diff
@@ -90,6 +90,15 @@
...
 }
 
+pre.shiki.nord > .code-container {
+  padding: var(--ifm-pre-padding);
+}
+
+pre.shiki.nord > .code-container > code {
+  display: block;
+  position: relative;
+}
```
Comment (StyleShit) [inline src/css/custom.css:100]: the error block is `position: absolute`, and the closest parent with `positon: relative` was too far and should've been the `code` tag itself.

**Review by JoshuaKGoldberg — APPROVED** [review]
Awesome, thanks @StyleShit! This is great 🙂 +1 especially on removing the duplicate elements!
